import { Grid, Typography } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <Grid>
      <Head>
        <title>LRS Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography
        variant="h4"
        sx={{ color: "primary.main", textAlign: "center" }}
      >
        Hello World
      </Typography>
    </Grid>
  );
}
